/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class itonlifecubeni_My3DesAlgorithm */

#ifndef _Included_itonlifecubeni_My3DesAlgorithm
#define _Included_itonlifecubeni_My3DesAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     itonlifecubeni_My3DesAlgorithm
 * Method:    Encrypt
 * Signature: ([B[B[BI)I
 */
JNIEXPORT jint JNICALL Java_itonlifecubeni_My3DesAlgorithm_Encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     itonlifecubeni_My3DesAlgorithm
 * Method:    Decrypt
 * Signature: ([B[B[BI)I
 */
JNIEXPORT jint JNICALL Java_itonlifecubeni_My3DesAlgorithm_Decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
