/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ItonLifecubeJni_NoiseReduction */

#ifndef _Included_ItonLifecubeJni_NoiseReduction
#define _Included_ItonLifecubeJni_NoiseReduction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ItonLifecubeJni_NoiseReduction
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ItonLifecubeJni_NoiseReduction_init
  (JNIEnv *, jobject);

/*
 * Class:     ItonLifecubeJni_NoiseReduction
 * Method:    Reduct
 * Signature: ([S[SI)I
 */
JNIEXPORT jint JNICALL Java_ItonLifecubeJni_NoiseReduction_Reduct
  (JNIEnv *, jobject, jshortArray, jshortArray, jint);

/*
 * Class:     ItonLifecubeJni_NoiseReduction
 * Method:    DenoiseClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ItonLifecubeJni_NoiseReduction_DenoiseClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
